### ISSUE TITLE
Incompatible with newest IDE

### ISSUE THREAD

**Issue by marcushoff** [kvakvs/intellij-yang#2]
After updating PyCharm to the newest version I get this error:

Plugin error: Plugin 'Yang Data Modeling Language' (version '2021.6.1') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PC-212.4746.96

**Comment by gabrielxfreire** [comment]
I have the same issue on IntelliJ IDEA ultimate.
<img width="298" alt="Screenshot 2021-09-15 at 19 39 43" src="https://user-images.githubusercontent.com/79519370/133490648-2b6c32c6-59ef-41d7-bd4b-6cb20bc3613d.png">

**Comment by marcushoff** [comment]
PyCharm IDE updated again and the error is back, just with build 212 this time.

**Comment by technikman** [comment]
Hi,

with the newest PyCharm version (2022.2.2) I get also an

_Plugin 'Yang Data Modeling Language' (version '2022.5.0') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is PY-222.4167.33_ Plugin Error

is it possible to Upgrade the Plugin?

**Comment by kvakvs** [comment]
Next published version will be compatible with 2023+
